### PR TITLE
Removing Rack::Cascade to properly handle 404s

### PR DESCRIPTION
**Pull request by ebfg**

### CODE REVIEW

**Comment by dblock** [comment]
Makes sense!

**Comment by dblock** [comment]
This actually breaks something else: https://github.com/dblock/grape-on-rack-v1-inside-v2/blob/eb017b4016ac95e46cf4483904c27e4c859e59e9/spec/api/v1_spec.rb#L21

If you have a method implemented in v2, but not in v1, you now get a 405 when you explicitly ask for v1, which is definitely wrong. With `Rack::Cascade` you don't, but then you have the original problem.

**Comment by dblock** [comment]
Oh never mind, this has something to do with memoizing an instance variable (probably in Grape?), removing `new` from `Acme::App.new` in tests solves this.

**Comment by ebfg** [comment]
:+1:

**Pull request merged**
